# Generated by Django 4.2.6 on 2023-11-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hexcode', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('long', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=510)),
                ('short_description', models.CharField(max_length=255)),
                ('features', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_cms', models.DecimalField(decimal_places=2, max_digits=8, unique=True)),
                ('size_inches', models.DecimalField(decimal_places=2, max_digits=8, unique=True)),
                ('UK', models.BigIntegerField(unique=True)),
                ('US', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_gms', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='products.color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='products.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='products.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant', to='products.size')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtype', to='products.type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BigIntegerField()),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='products.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='products.variant')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.subtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.usage'),
        ),
        migrations.CreateModel(
            name='InventoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_stocks', models.BigIntegerField()),
                ('restock_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_details', to='products.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_details', to='products.variant')),
            ],
        ),
    ]
