# Generated by Django 4.2.6 on 2023-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_address_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_name',
            field=models.CharField(default='Contact Name', max_length=100),
        ),
    ]
